spring:
  mail:
    test-connection: true
    host: smtp.gmail.com
    #host: m.outlook.com
    port: 587
    username: edsonariel@gmail.com
    password: pwd
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 25000
          timeout: 25000
          writetimeout: 25000
  secret:
    tokenKey: JszuZl0vV+SwgyI08+zpQ6Hhp3Epr3Zxuy/8UFSLBOSUJWkm1havRtdabryNCrklfCSXom9K9nuMxbCX5TR+8ceoNsArkX6on9dn+4hY+GH3gL11/mROgd42cSoPAxiLEBqJHRhlQZgijRygMR63OffGKAd8OW5V4zCixQEeUI9Ql5Ay+GStqXK7Cp4447a68R8HnhqWTroKNHXaFZC+k4AdjGCjsU1GaWIvie7pmHSOq49nP9Lsv1cGVghXG42ozde/mze0hdODqzBOwPrREcI1SpzOr2jgMNfRx4PuPBaezuUhkaAhXwi+uu3QjXki24Ld4HIBwaBJ6hNFtB1B+A==
